export const EMAIL_MESSAGE_REPOSITORY = Symbol('EMAIL_MESSAGE_REPOSITORY');
export const EMAIL_AI_ANALYSIS_ADAPTER = Symbol('EMAIL_AI_ANALYSIS_ADAPTER');
export const PROCESSED_EMAIL_TRACKER = Symbol('PROCESSED_EMAIL_TRACKER');
