export const INQUIRY_REPOSITORY = Symbol('INQUIRY_REPOSITORY');
export const INQUIRY_MESSAGE_REPOSITORY = Symbol('INQUIRY_MESSAGE_REPOSITORY');
export const CUSTOMER_REPOSITORY = Symbol('CUSTOMER_REPOSITORY');
export const INQUIRY_STATUS_LOG_REPOSITORY = Symbol('INQUIRY_STATUS_LOG_REPOSITORY');
