export const EMAIL_MESSAGE_REPOSITORY = Symbol('EMAIL_MESSAGE_REPOSITORY');
export const EMAIL_AI_ANALYSIS_ADAPTER = Symbol('EMAIL_AI_ANALYSIS_ADAPTER');
export const PROCESSED_EMAIL_TRACKER = Symbol('PROCESSED_EMAIL_TRACKER');
export const EMAIL_THREAD_REPOSITORY = Symbol('EMAIL_THREAD_REPOSITORY');
export const AI_DECISION_REPOSITORY = Symbol('AI_DECISION_REPOSITORY');
