export const CONTEXT_SNAPSHOT_REPOSITORY = Symbol('CONTEXT_SNAPSHOT_REPOSITORY');
export const TOKEN_ESTIMATOR = Symbol('TOKEN_ESTIMATOR');
export const RAG_RETRIEVER_ADAPTER = Symbol('RAG_RETRIEVER_ADAPTER');
